---
# tasks file for aws_instance
  - name: Installing boto3 lib
    pip:
      name: "boto3"

  - name: Launching instance 1
    ec2_instance:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      image_id: "ami-068d43a544160b7ef"
      instance_type: t2.micro
      key_name: "arth-client"
      region: "ap-south-1"
      name: "k8s-master"
      security_group: RDSWP
      state: started
      wait_timeout: 15
    register: inst1_info

  - debug:
      var: inst1_info

  - name: Launching instance 2
    ec2_instance:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      image_id: "ami-068d43a544160b7ef"
      instance_type: t2.micro
      key_name: "arth-client"
      region: "ap-south-1"
      name: "k8s-slave1"
      security_group: RDSWP
      state: started
      wait_timeout: 15
    register: inst2_info


  - debug:
      var: inst2_info

  - name: Launching instance 3
    ec2_instance:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      image_id: "ami-068d43a544160b7ef"
      instance_type: t2.micro
      key_name: "arth-client"
      region: "ap-south-1"
      name: "k8s-slave2"
      security_group: RDSWP
      state: started
      wait_timeout: 15
    register: inst3_info

  - debug:
      var: inst3_info
      
  - pause:
      minutes: 1 

  - name: Update the inventory
    blockinfile:
      dest: /root/ip.txt
      marker: ""
      block: |
       [aws_instance_master]
       {% for i in [inst1_info] %}
       {{ i["instances"][0]["public_ip_address"] }} ansible_user=ec2-user ansible_ssh_private_key_file=arth-client.pem
       {% endfor %}
       [aws_instance_slave]
       {% for i in [inst2_info,inst3_info] %}
       {{ i["instances"][0]["public_ip_address"] }} ansible_user=ec2-user ansible_ssh_private_key_file=arth-client.pem
       {% endfor %}
       [aws_instance:children]
       aws_instance_master
       aws_instance_slave
  - name: "Refresh the inventory"
    meta: refresh_inventory
