---
# tasks file for slave
  - name: "iproute"
    copy:
      dest: "/etc/sysctl.d/k8s.conf"
      content: |
             net.bridge.bridge-nf-call-ip6tables = 1
             net.bridge.bridge-nf-call-iptables = 1
  - shell: "sysctl --system"

  - name: "Joining the slave node"
    command: "{{ join_cmd }}"
